### PR TITLE
Travis ci

### PR DESCRIPTION
**Pull request by piiertho**
Hi !  
Here is a PR for travis CI ! It assures code compiles for each platforms and provide a way to release for each platform (just by creating a release in github, the tag will be triggered, as you can see [here](https://github.com/piiertho/godot-fmod-integration/releases)).  
You should provide some environment variable to your travis :  
- ANDROID_NDK_ROOT: you should set it to /home/travis/build/alexfonseka/android-sdk/ndk-bundle. (it should be readable in console)
- FMODUSER: A fmod user to download fmod api. (should not be visible in console)
- FMODPASS: the password corresponding to FMODUSER. (should not be visible in console)
- TRAVIS_TOKEN: a github personal access token to deploy release. (should not be visible in console)

Hope you'll enjoy it !

### CODE REVIEW

**Comment by heraldofgargos** [comment]
Magnificent. I will set this up as soon as I have the time. Distributing compiled versions of the engine as part of the release seems like a great idea so users (specially sound designers and composers) won't have to go through the process of recompiling the engine.

**Review by heraldofgargos — COMMENTED** [review]
It seems like there is an issue with the download-fmod script. I'll have a closer look.

**Comment by piiertho** [comment]
Hi !
I did not get any problem on my side using the script : https://travis-ci.com/piiertho/godot-fmod-integration.
It seems it does not go after the first request:
```
curl -X POST -u $1:$2 https://www.fmod.com/api-login
```
Did you set valid Fmod account travis environment variables FMODUSER and FMODPASS in travis ci interface ?
It also seems there are some compilation errors on Linux, MacOS, and Android ARM64 since master merge.

**Comment by heraldofgargos** [comment]
Hey there.
> Did you set valid Fmod account travis environment variables FMODUSER and FMODPASS in travis ci interface ?

Yeah it's set up in my repository settings on Travis. I'm guessing Travis doesn't make them available for forks and PRs.
> It also seems there are some compilation errors on Linux, MacOS, and Android ARM64 since master merge.

Yep it seems like a data type issue. I'll push a fix for it soon.

**Comment by piiertho** [comment]
Hi Alex !

I had same data type issue on GDNative side, I used static cast to handle it.
Maybe it could be simpler if we see CI with skype or discord ?

**Comment by heraldofgargos** [comment]
Pushed a fix 2e8dff5 to address the type issue on Linux and Android64.

**Comment by heraldofgargos** [comment]
Merged and build passed! All good.
Thanks for setting up Travis! 👍

**Pull request merged**
